### PR TITLE
Fixed instrumentation counter in IntelliJ verifier

### LINKED ISSUE #211: `Verify` task error says about "lines" when counterType is Branch or Instruction
0.6.0-Beta

Set counter for verify task INSTRUCTION or BRANCH:
```
verify {
            ...
                bound {
                    minValue = 20
                    maxValue = 20
                    counter = kotlinx.kover.api.CounterType.BRANCH 
                    valueType = kotlinx.kover.api.VerificationValueType.COVERED_COUNT
                }
            }
```
In case of error it will always be about lines:
`Rule 'test' violated: missed lines percentage is 75.000000, but expected maximum is 20`
Expected:
`Rule 'test' violated: missed instructions/branches percentage is 75.000000, but expected maximum is 20`

### PR DESCRIPTION
**Pull request by shanshin**
- IntelliJ Engine version upgraded to 1.0.680
- added tests on verification error

Fixes #211, #210, #212

### CODE REVIEW

File: src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/VerificationTests.kt [hunk 1]
```diff
@@ -57,55 +57,93 @@ internal class VerificationTests : BaseGradleScriptTest() {
...
-            output {
-                assertTrue {
-                    this.contains(
-                        "[ant:jacocoReport] Rule violated for bundle :: lines covered ratio is 0.50, but expected minimum is 0.58\n" +
-                                "[ant:jacocoReport] Rule violated for bundle :: lines covered count is 4, but expected maximum is 3"
-                    )
-                }
+        build.prepare().runWithError("koverHtmlReport", "koverVerify") {
+            verification {
+                assertIntelliJResult("""Rule 'counts rule' violated:
```
Comment (qwwdfsad) [inline src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/VerificationTests.kt:101]: Works for me, but in case when there is more than one such test, I would suggest extracting test data (these long strings) into `test-resources` text files available by `@TestName` similarly to this:

**Review by qwwdfsad — APPROVED** [review]

File: src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/VerificationTests.kt (hunk 1 above)
Comment (shanshin) [reply src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/VerificationTests.kt:101]: I think yes, with an increase in the number of verification tests, these lines should be put into files.
