### PR TITLE
Fixed warning for empty Kotlin plugin configuration

### LINKED ISSUE #701: Coverage report is generating for a springboot + maven project, but there is an NPE
Hello,

I have just added kover with my spring boot project. I can run tests and also generate coverage reports. But there is this NPE:

img

Though the coverage is generated. Can you please tell me I'm doing something wrong? Or what could resolve this.

Here is a minimal project that generates this issue:

https://github.com/Ruhshan/springboot-maven-kt

### PR DESCRIPTION
**Pull request by shanshin**
When a configuration is specified in the execution for the `compile` target, but the `sourceDirs` child element is missing, an error occurred. A check has been added to fix the error.

Fixes #701

### CODE REVIEW

File: kover-maven-plugin/src/main/kotlin/kotlinx/kover/maven/plugin/mojo/abstracts/AbstractCoverageTaskMojo.kt [hunk 1]
```diff
@@ -226,7 +226,9 @@ abstract class AbstractCoverageTaskMojo : AbstractKoverMojo() {
                 .filter { "compile" in it.goals }
                 .filter { execution -> execution.configuration != null && execution.configuration is Xpp3Dom }
                 .flatMap { execution ->
-                    (execution.configuration as Xpp3Dom).getChild("sourceDirs").children.map { toAbsoluteFile(it.value) }
+                    val config = execution.configuration as Xpp3Dom
+                    val sourceDirs = config.getChild("sourceDirs") ?: return@flatMap emptyList()
+                    sourceDirs.children.map { toAbsoluteFile(it.value) }
```
Comment (sandwwraith) [inline kover-maven-plugin/src/main/kotlin/kotlinx/kover/maven/plugin/mojo/abstracts/AbstractCoverageTaskMojo.kt:231]: If there are `<sourceDirs><sourceDirs/>`, but no children are specified, will `children` be a null or an emptyList?

**Review by sandwwraith — APPROVED** [review]

File: kover-maven-plugin/src/main/kotlin/kotlinx/kover/maven/plugin/mojo/abstracts/AbstractCoverageTaskMojo.kt (hunk 1 above)
Comment (shanshin) [reply kover-maven-plugin/src/main/kotlin/kotlinx/kover/maven/plugin/mojo/abstracts/AbstractCoverageTaskMojo.kt:231]: Empty list, it's not mentioned in the docs, but implementation is
```
    public Xpp3Dom[] getChildren()
    {
        if ( null == childList || childList.isEmpty() )
        {
            return EMPTY_DOM_ARRAY;
        }
        else
        {
            return (Xpp3Dom[]) childList.toArray( new Xpp3Dom[childList.size()] );
        }
    }
```
