### PR TITLE
Fixed issues with cache miss of build cache at the time of relocation

### LINKED ISSUE #413: Kover is causing cache misses in Gradle Enterprise.
**Describe the bug**
A gradle cache miss is occurring when using the kover gradle plugin

I think this needs to be changed to Relative rather than absolute:
https://github.com/Kotlin/kotlinx-kover/blob/21aa8b302a4185502948110fc85d2be8f2fddf99/kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverAgentJarTask.kt#LL25C40-L25C48

**Errors**
See example cache miss from a gradle build scan:
image

**Expected behavior**
Cache hits

**Reproducer**
A link to your project, if it is open source. Otherwise, please try to reproduce the problem on a small project. 
If this is not feasible, give an example of the code on which the problem manifests itself. 

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: 0.7.1
 - Gradle version: 8.1.1
 - Kotlin project type: Kotlin/JVM
 - Coverage Toolset Kover
 - Other context important for this bug: Linux/MacOS

### PR DESCRIPTION
**Pull request by shanshin**
Using `PathSensitivity.ABSOLUTE` in all cases will lead to a cache miss

Fixes #413

### CODE REVIEW

File: kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BuildCacheRelocationTests.kt [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+        val result1 = gradleBuild1.runWithParams("koverXmlReport", "koverHtmlReport", "koverVerify", "--build-cache")
+        assertEquals("SUCCESS", result1.taskOutcome(":test"))
+        assertEquals("SUCCESS", result1.taskOutcome(":koverGenerateArtifact"))
+        assertEquals("SUCCESS", result1.taskOutcome(":koverXmlReport"))
+        assertEquals("SUCCESS", result1.taskOutcome(":koverHtmlReport"))
+        assertEquals("SUCCESS", result1.taskOutcome(":koverVerify"))
+
+        /*
+        since the build is created from a template,
+        repeat generation will create a new directory with exactly the same contents as the previous one.
```
Comment (sandwwraith) [inline kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BuildCacheRelocationTests.kt:38]: So 'relocation' here means relocation of the project, not the cache?

File: kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/JvmTestTaskConfigurator.kt [hunk 2]
```diff
@@ -59,8 +59,9 @@ private class JvmTestTaskArgumentProvider(
     private val tempDir: File,
     private val toolProvider: Provider<CoverageTool>,
 
+    // relative sensitive for file - this is a comparison by file name and its contents
```
Comment (sandwwraith) [inline kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/JvmTestTaskConfigurator.kt:62]:
```suggestion
    // relative sensitivity for file is a comparison by file name and its contents
```

File: kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverAgentJarTask.kt [hunk 3]
```diff
@@ -21,8 +21,9 @@ import javax.inject.*
  */
 @CacheableTask
 internal abstract class KoverAgentJarTask : DefaultTask() {
+    // relative sensitive for file collection which are not FileTree  - this is a comparison by file name and its contents
```
Comment (sandwwraith) [inline kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverAgentJarTask.kt:24]:
```suggestion
    // relative sensitivity for file collections which are not FileTree is a comparison by file name and its contents
```

**Review by sandwwraith — APPROVED** [review]

File: kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BuildCacheRelocationTests.kt (hunk 1 above)
Comment (shanshin) [reply kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BuildCacheRelocationTests.kt:38]: Yes, when the project is moved to another directory
